const dataEn = {
    'header__content1_1title': 'Do you want to register your trademark?',
    'header__content1_1descr': 'A team of specialists from the law firm "Simay Kom" with more than 10 years of experience, is ready to provide you with their services.',
    'slider__item-title': 'Our recent affairs:',
    'slider__item1_1descr__title_lang@': 'The court`s decision',
    'slider__item1_1descr__text_1': 'Participation in the economic court of the city of Tashkent on the claim of the Limited Liability Company "SFERA IMPORT SOLUTIONS" against the Limited Liability Company "Confectionery Factory named after N.K. Krupskaya "on early termination of the international registration No. 719739 for the trademark" Belochka "in respect of goods of the 30th class of MKTU in the territory of the Republic of Uzbekistan due to its non-use.',
    'slider__item1_1descr__text_2': 'By a court decision dated January 22, 2019, SFERA IMPORT SOLUTIONS LLC was rejected the claim. The effect of the international registration for the "Belochka" trademark on the territory of the Republic of Uzbekistan has been preserved.',
    'slider__item1_1descr__text_3@': 'The decision of the economic court of the city of Tashkent is attached.',
    'slider__item1_1descr__text_4': 'Participation jointly with the patent attorney of the Republic of Uzbekistan A.A. Borzenko in the economic court of the city of Tashkent on the claim of the Limited Liability Company "ALI-RIZO GOLD BIZNES" with the claim against the Limited Liability Company "Grin" on the early termination of the international registration No. 1176825 on the trademark "GRASS" in the part of goods 03 class MKTU, due to its non-use. The interests of LLC "Grin" were represented.',
    'slider__item1_1descr__text_5': 'By a court decision of 12.02.2019, ALI-RIZO GOLD BIZNES LLC was rejected to satisfy the claims. The effect of the international registration for the "GRASS" trademark on the territory of the Republic of Uzbekistan is preserved.',
    'slider__item1_1descr__text_6': 'Participation jointly with the patent attorney of the Republic of Uzbekistan A.A. Borzenko in the administrative court of the Mirzo-Ulugbek district of the city of Tashkent on the application of the Joint Stock Company "LEKHIM" to invalidate the decision by the Intellectual Property Agency of the Republic of Uzbekistan "on the registration of the trademark" PROSTATILEN / PROSTATILENUM "in the name of MBNPK" Cytomed "CJSC. The interests of ZAO MBNPK "Cytomed" were represented.',
    'slider__item1_1descr__text_7': 'By a court ruling dated March 28, 2019, the proceedings were terminated. By the decision of the appellate instance of the administrative court of the city of Tashkent dated 05/08/2019, the court ruling was left unchanged, and the appeal was not satisfied.',
    'services__title_1': 'Trademark protection services:',
    'services__item-descr_1': 'Representation and protection of the interests of the Principal in all bodies of state power and administration, in any institutions and organizations, regardless of the form of ownership, in front of all legal entities and individuals of the Republic of Uzbekistan;',
    'services__item-descr_2': 'Representing the interests of the client in the Appeal Council of the Ministry of Justice in the Republic of Uzbekistan;',
    'services__item-descr_3': 'Representing the interests of the Principal in court;',
    'services__item-descr_4': 'Representation of interests in the antimonopoly committee;',
    'services__item-descr_5': 'Representation of interests in customs authorities;',
    'services__title_2': 'Our other services:',
    'services__item-descr_6': 'Translation of patent documents into:',
    'services__item-descr_7': 'English',
    'services__item-descr_8': 'Russian and',
    'services__item-descr_9': 'Uzbek languages',
    'symbol__title': 'As trademarks may be registered:',
    'symbol__item-descr_1': 'Pictorial',
    'symbol__item-descr_2': 'Verbal',
    'symbol__item-descr_3': 'And other designations or their combinations in any color or color combination',
    'registration__title': 'Trademark registration services',
    'doubt__title': 'Do you doubt whether your trademark can be registered?',
    'form__text': 'Leave a request and our specialists will quickly contact you and conduct a free consultation.',
    'form__input_1@': 'Name',
    'form__input_2@': 'Phone',
    'form__textarea_1': '',
    'principle__title': 'Our paramount principles:',
    'principle__info-text_1': 'A qualified approach to solving the task in the shortest possible time and in strict accordance with the legislation',
    'principle__info-text_2': 'Strict execution of the client`s instructions within the timeframe set by him',
    'principle__info-text_3': 'Providing the client with complete information on issues of interest',
    'principle__info-text_4': 'Impeccable preparation of documents for registration of trademarks and their timely submission to the State Patent Office',
    'principle__info-text_5': 'Improving the quality of services through improving the forms and methods of work',
    'principle__info-text_6': 'Providing discounts to regular customers. We are flexible in setting the amount and procedure for payment for our services, and we adhere to these principles when working with any principals, regardless of their status and financial situation',
    'map__contact-title': 'Our contacts',
    'btn--request@': 'Send',
    'btn--modal@': 'Get consultation',
    'registration__item-text_1': 'Consulting on the provision of legal protection to a trademark, service mark and appellation of origin.',
    'registration__item-text_2': 'Conducting an information search on the fund of trademarks registered and declared for registration in the Republic of Uzbekistan to assess the possibility of registering the declared designation.',
    'registration__item-text_3': 'Registration of trademarks, service marks, appellations of origin. Representing the interests of the client in the Intellectual Property Agency under the Ministry of Justice of the Republic of Uzbekistan on registration and legal protection of a trademark, including prior to the appeal settlement of disputes.',
    'registration__item-text_4': 'Renewal of the certificate for trademarks and service marks.',
    'registration__item-text_5': 'Drawing up contracts for the assignment of rights to a trademark and licensing agreements with registration with the Agency for Intellectual Property under the Ministry of Justice of the Republic of Uzbekistan.'
}

// const dataEnSecond = {
    
// }

export default dataEn;